interface:
  title: "RoBERTa Spanish Chat"
  temperature:
    min: 0.0
    max: 1.0
    default: 0.7
    step: 0.1
  max_length:
    min: 64
    max: 512
    default: 256
    step: 64
  placeholder: "Escribe tu mensaje aquí..."
